package com.app.inails.booking.admin.model.response

 

data class RecruitmentDTO(
    val contact_email: Any,
    val created_at: String? = "",
    val deadline_submission: Any,
    val deleted_at: Any,
    val description: String? = "",
    val experience_required: Double? = 0.0,
    val type_salary: Int? = 1,
    val id: Int? = 0,
    val images: List<AppImage>,
    val position: Int? = 0,
    val position_name: String? = "",
    val position_other: String? = "",
    val quantity: Any,
    val salary: Double? = 0.0,
    val salary_format: String? = "",
    val salon: SalonDTO,
    val salon_id: Int? = 0,
    val short_description: Any,
    val status: Int? = 0,
    val status_name: String? = "",
    val title: String? = "",
    val updated_at: String? = "",
    val view: Int,
    val working_form: Int? = 0,
    val working_form_name: String?= "",
    val working_term: Int? = 0,
    val gender: Int? = 1,
    val work: Int? = 1,
    val customer_skin_color: Int? = 1,
    val income_weekly: Double? = 0.0,
    val is_shuttle: Int? = 0,
    val is_there_house: Int? = 0,
    val skills: List<SkillDTO>? = listOf(),
    val salary_form: Int = 0,
    val salon_exists_time: Int = 0,
    val contact_name: String? = "",
    val salon_name: String? = "",
    val contact_phone:String? = "",
    val salon_city: String?= "",
    val salon_state: String? = "",

)